// data/jobs.ts
import { Job } from "@/types/job.type";

export const jobs: Job[] = [
  {
    id: 1,
    slug: "senior-frontend-developer",
    title: "Senior Frontend Developer",
    company: "TechCorp Vietnam",
    location: "Ho Chi Minh City",
    type: "Toàn thời gian",
    mode: "Hybrid",
    level: "Senior",
    salaryMin: "2000",
    salaryMax: "3000",
    salaryCurrency: "USD",
    description:
      "Phát triển và tối ưu ứng dụng web với React/TypeScript, phối hợp team backend và design.",
    requirements:
      "3+ năm kinh nghiệm, vững React/TS, nắm vững HTML/CSS, Git workflow, tối ưu hiệu năng.",
    benefits:
      "Lương thưởng cạnh tranh, bảo hiểm full, hỗ trợ học tập và thời gian linh hoạt.",
    deadline: "2024-02-15",
    email: "hr@techcorp.vn",
    urgent: false,
    featured: true,
    posted: "2024-01-15",
    expires: "2024-02-15",
    status: "active",
    applications: 24,
    views: 156,
    skills: ["React", "TypeScript", "Git", "Figma"],
  },
  {
    id: 2,
    slug: "ui-ux-designer",
    title: "UI/UX Designer",
    company: "Designify",
    location: "Hanoi",
    type: "Toàn thời gian",
    mode: "Văn phòng",
    level: "Mid",
    salaryMin: "1200",
    salaryMax: "2000",
    salaryCurrency: "USD",
    description: "",
    requirements: "",
    benefits: "",
    deadline: "2024-02-10",
    email: "hr@designify.vn",
    urgent: false,
    featured: false,
    posted: "2024-01-10",
    expires: "2024-02-10",
    status: "active",
    applications: 18,
    views: 89,
    skills: [],
  },
  {
    id: 3,
    slug: "backend-developer",
    title: "Backend Developer",
    company: "ServerSide Co.",
    location: "Da Nang",
    type: "Toàn thời gian",
    mode: "Remote",
    level: "Mid",
    salaryMin: "1800",
    salaryMax: "2800",
    salaryCurrency: "USD",
    description: "",
    requirements: "",
    benefits: "",
    deadline: "2024-01-20",
    email: "careers@serverside.co",
    urgent: false,
    featured: false,
    posted: "2023-12-20",
    expires: "2024-01-20",
    status: "expired",
    applications: 32,
    views: 203,
    skills: [],
  },
];