version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      -'${APP_PORT}:3000'
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network
networks:
  app-network:
    driver: bridge